before:
  hooks:
    - go mod tidy
env:
  - CGO_ENABLED=0
builds:
  - id: datactl
    main: ./cmd/datactl
    binary: datactl
    targets:
      - linux_amd64
      - linux_s390x
      - linux_arm64
      - linux_ppc64le
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
  - id: oc-datactl
    main: ./cmd/datactl
    binary: oc-datactl
    targets:
      - linux_amd64
      - linux_s390x
      - linux_arm64
      - linux_ppc64le
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
archives:
  - id: tar
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      amd64: x86_64
      darwin: Darwin
      linux: Linux
      windows: Windows
    builds:
      - datactl
      - oc-datactl
    format: tar
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
