before:
  hooks:
    - go mod tidy
env:
  - CGO_ENABLED=0
builds:
  - id: rhmctl
    main: ./cmd/rhmctl
    binary: rhmctl
    targets:
      - linux_amd64
      - linux_s390x
      - linux_arm64
      - linux_ppc64le
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
  - id: oc-rhmctl
    main: ./cmd/rhmctl
    binary: oc-rhmctl
    targets:
      - linux_amd64
      - linux_s390x
      - linux_arm64
      - linux_ppc64le
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
archives:
  - id: tar
    builds:
      - rhmctl
      - oc-rhmctl
    format: binary
    files:
      - hack/token-job.yaml
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
