name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Ginkgo
        run: |
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega/...

      - name: Test
        run: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: github.ref != 'refs/heads/main'
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist

      - name: Archive build
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
